name: Manual Trigger Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: Select Build type
        required: true
        default: 'debug'
        options:
          - debug
          - releaseDebug
          - release
          - appBundle

      version:
        type: build_type
        description: Enter BuildName / BuildVersion
        required: true
        default: '1.0.0'

env:
  RELEASE_VERSION: ""
  BUILD_TOOLS_VERSION: ""

jobs:
  debug:
    name: debug
    if: ${{ github.event.inputs.buildType == 'debug' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembledebug

      - name: Upload Apk
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

  release:
    name: release
    if: ${{ github.event.inputs.buildType == 'release' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate a Release Apk
        run: ./gradlew assemblerelease

      - name: Setup build tool version variable
        shell: bash
        run: |
          TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "TOOL_VERSION=$TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $TOOL_VERSION

      - name: Update Build Tools Version
        run: echo "BUILD_TOOLS_VERSION=$TOOL_VERSION" >> $GITHUB_ENV

      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app_release
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}

      - name: Upload Release Apk
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-release.apk
          path: ${{steps.sign_app_release.outputs.signedReleaseFile}}
          retention-days: 30

  appBundle:
    name: appBundle
    if: ${{ github.event.inputs.buildType == 'appBundle' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Get APK Version Code
        env:
          VERSION_CODE: $(grep "versionCode" build.gradle | awk '{print $3}')
          VERSION_NAME: $(grep "versionName" build.gradle | awk '{print $3}'| tr -d "'\"[:space:]\n" )
        run: |
          APP_VERSION=$(printf "%s%s" "${{ env.VERSION_CODE }}" " (${{ env.VERSION_NAME }})")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "$APP_VERSION"

      - name: Update Release Version
        run: echo "RELEASE_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate a App Bundle
        run: ./gradlew bundleRelease

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-release.aab
          path: ${{steps.sign_app_bundle.outputs.signedReleaseFile}}
          retention-days: 3

      - name : Internal Sharing Bundle Upload On Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.tul.tatacliq
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          releaseName : ${{ env.RELEASE_VERSION }}
          whatsNewDirectory : distribution/
          track: internal
          status: completed
          inAppUpdatePriority : 4
